services:
  redis:
    container_name: voter-redis
    restart: on-failure
    image: "redis/redis-stack:7.2.0-v8"
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - db
  web:
    container_name: voter-web
    restart: on-failure
    image: "agentjsmith/voter-container"
    environment:
      - "VOTER_API_REDIS_ADDR=redis:6379"
    ports:
      - "1080:1080"
    depends_on:
      - redis
    networks:
      - dmz
      - db
networks:
  dmz:
    internal: false
  db:
    internal: true